name: gis-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - gdal=3.8.5
  - fiona
  - geopandas
  - shapely
  - pyproj
  - folium
  - matplotlib
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - requests
  - pip
  - cmake
  - boost-cpp
  - pip:
    - future==1.0.0
    - pyogrio==0.11.1
    - h3
    - s2sphere
    - rtree
    - pygeohash
